/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.1.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement { includeBuild("build-logic") }

rootProject.name = "quickbite"

include(
    "libs:common",
    // Commented out until these service directories are scaffolded — Gradle refuses to
    // configure a project whose directory doesn't exist, which was breaking sync and
    // Ctrl+click navigation in the Java extension. Re-enable as each module is created.
    // "services:gateway",
    // "services:catalog-svc",
    // "services:order-svc",
    // "services:payment-svc",
    // "services:location-svc",
    // "services:realtime-svc",
)
